services:
  - type: web
    name: goc-hoc-tap-demo
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Goc hoc tap cua em
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_LOG
        value: errorlog
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: goc-hoc-tap-demo
          envVarKey: RENDER_EXTERNAL_URL
      - key: STAGING_DEMO
        value: "true"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_DRIVER
        value: sync
      - key: MAIL_DRIVER
        value: log
